### ISSUE TITLE
Gestion des styles par workspace?

### ISSUE THREAD

**Issue by jpklipfel** [georchestra/data-admin-book#1]
Hello,

J'ouvre le bal avec une question particulière d'un admin de données

Je me demandais ce matin s'il fallait affecter les styles aux workspaces? ayant pris cette habitude dans une logique mon layer est dans un workspace donc le style y sera également.

Inconvénients de cette pratique
- Si on est intéressé par réutiliser ce style dans un autre wokspace
- Je ne les retrouve pas via l'api rest (gs 2.8.3) ils devraient normalement être dans /workspaces/<ws>/styles[.<format>]

Avantages
- On ne propose pas moultes styles dans le cas de délégation d'admin sur un workspace

Ici http://gis.stackexchange.com/questions/47976/problem-with-styles-having-a-workspace
Ils recommandent de ne pas le faire, j'aurais tendance à les suivre

Qu'en pensez vous?

Est ce que ce type de recommandation aurait sa place dans le data-admin-book?

**Comment by landryb** [comment]
Si tu ne vois pas tes styles dans /workspaces/ws/styles c'est qu'il y'a un bug qqpart.. ici, ca marche bien (gs 2.8.1) et dans l'endpoint REST /styles je n'ai que les 5 styles 'globaux' fournis par défaut par GS (raster/point/generic/line/polygon).

Je sais que je fais pareil (mettre les styles dans le WS) car si tu delegue l'admin uniquement sur un WS, je crois que l'admin du WS ne peut qu'affecter des styles provenant du WS, et pas de styles 'globaux'.

Le lien que tu mets sur stackexchange date de 2013 et est sur GS 2.4, il y'a eu du chemin de fait depuis....

**Comment by jpklipfel** [comment]
> Si tu ne vois pas tes styles dans /workspaces/ws/styles c'est qu'il y'a un bug qqpart...

OK merci

> car si tu delegue l'admin uniquement sur un WS, je crois que l'admin du WS ne peut qu'affecter des styles provenant du WS, et pas de styles 'globaux'.

Testé ce matin, il voit les globaux et ceux de son WS
Je trouvais intéressante l'idée de proposer des styles qui ont servi à d'autre à l'admin délégué. Je pense qu'il y a peu ou pas de cas de styles privés

Du coup la recommandation serait plutôt chaqu'un fait comme il veut?

**Comment by landryb** [comment]
Je pense que l'idée serait 'si on sait que certaines couches vont etre présentes plusieurs fois dans X ws, proposer un style commun dans les globaux', comme ca (si besoin) l'admin du ws local peut le copier/surcharger, et sinon il colle ses styles dans son WS (vu que c'est le seul endroit ou il peut écrire).

Dans le cas ou tu as un seul admin global,.... j'avoue ne pas bien voir les avantages/inconvénients des 2 méthodes.

**Comment by lecault** [comment]
GéoBretagne a depuis peu des admin délégués qui peuvent uniquement créer et modifier des styles dans leur workspace. Du coup j'ai déplacé les leurs dedans. Néanmoins, ils peuvent utiliser des styles du workspace global.

Après on a pas de règle claire : je suis plutôt pour mettre les styles dans le ws global (pour utilisation massive) mais nous avions utilisé les ws pour des styles se répétant dans plusieurs ws.

Ex : le style est nommé aire_covoiturage dans les ws de chaque département car l'analyse peut varier.

**Comment by jpklipfel** [comment]
Voici une proposition de contribution pour la partie 
- connaitre la logique espace de nommage / entrepôt / couche / agrégation / style ...

Geoserver est organisé par espaces de nommage et laisse la possibilité à l'administrateur de garder l'endpoint ouvert ou non.

Il faut savoir que GeoWebCache a besoin de l'endpoint ouvert pour fonctionner (GS 2.8). De plus avec un endpoint fermé, on ne pourra plus monter des couches agrégées venant d'espaces de nommage différents (sauf à devoir les dupliquer).

En cas d'un grand nombre de couches dans Geoserver, un getcapabilities sur l'endpoint peut être lent. Il est néanmoins possible de le garder ouvert mais de ne pas utiliser ou communiquer les appels sur l'url globale Geoserver.

Généralement les IDS organisent leurs espaces de nommage par partenaires afin de pouvoir leur déléguer la création des couches et des styles (on parle d'administration déléguée).

Les acronymes choisis pour les espaces de nommage devraient être le plus générique possible étant donné que les appellations changent (typiquement Conseil Général en Conseil Départemental). En cas de changement cette mise à jour n'est pas simple et on peut être amené à devoir recréer tous les entrepôts, les couches et les styles (via gsconfig par exemple). Un resolver pourrait accompagner le changement dans la douceur. En tous cas, il n'est pas conseillé de modifier le datadir à la main sans assurance.

Les styles seraient à organiser par espaces de nommage sauf pour ceux susceptibles d'intéresser d'autres utilisateurs.

Dans le choix des noms des couches, il est conseillé de prendre des appellations génériques type ortho67_2015 ce qui aurait l'avantage de pouvoir être réutilisable si au fil du temps on modifie un format de publication par exemple. La stabilité des chemins d'accès aux couches est très importante pour les applications tierces qui consomment les données.

**Comment by jpklipfel** [comment]
https://github.com/georchestra/data-admin-book/pull/2
