### ISSUE TITLE
Organisation de la doc

### ISSUE THREAD

**Issue by jpklipfel** [georchestra/data-admin-book#3]
Vous avez défini une autre orga durant le sprint ?
Je vois des choses redondantes entre 
>data-admin-book\fr\02_geoserver\02_publish_data.md

et
>data-admin-book\fr\guide-administrateur\geoserver\creer-un-lien-entre-les-metadonnees-et-les-donnees.md

par exemple

d'ailleurs il y a deux 
>data-admin-book\fr\guide-administrateur

**Comment by zchicago** [comment]
je ne vois pas a quoi tu fais référence? pourrais tu preciser s'il te plait 
FYI le gitbook est accessible via https://www.gitbook.com/@georchestra

**Comment by jpklipfel** [comment]
OK j'ai eu du mal a m'y retrouver dans l'organisation des dossiers, le mieux serait peut être d'éditer avec gitbook
Comment demander les droits d'édition?

**Comment by fvanderbiest** [comment]
Apparemment gitbook ou l'usage qui en a été fait ne permete pas de supprimer les vieilles pages...
Et oui, l'organisation du book a été revue par les participants du sprint, tout est dans https://github.com/georchestra/data-admin-book/tree/master/fr/guide-administrateur maintenant.

Je te donne les droits d'édition via gitbook ASAP

**Comment by jpklipfel** [comment]
up pour les droits @fvanderbiest

**Comment by fvanderbiest** [comment]
Je viens de t'envoyer une invitation

**Comment by MaelREBOUX** [comment]
Un truc pas clair pour moi : à chaque doc / guide il faut bien un dépôt à part du code source ?

Genre pour cadastrapp il va falloir créer un dépôt "cadastrapp_doc" ?
Pour le module urbanisme un dépôt "urbanisme_doc" ?

**Comment by zchicago** [comment]
Durant le doc sprint on s'est effectivement dit que ce qui ne faisait pas partie du coeur de geOrchestra aurait une partie a part.Avec le recul ça te parait trop lourd comme organisation?

**Comment by jpklipfel** [comment]
>Je viens de t'envoyer une invitation

Peux tu refaire stp? je n'ai rien vu passer

**Comment by fvanderbiest** [comment]
Fait. Sinon crées toi un compte sur gitbook et donnes moi ton login.

**Comment by jpklipfel** [comment]
Toujours rien, du coup j'ai crée jp-klipfel

**Comment by fvanderbiest** [comment]
Should be good.

**Comment by jpklipfel** [comment]
Perfect thanks!

Je laisse le ticket ouvert pour la discussion ce qui rentre ou pas dans cette doc ?

Un passage sur sdi-consistence-check ou paramétrage du sviewer pourrait être utile ou alors sous la forme de lien vers les readme

**Comment by zchicago** [comment]
hello,
le passage pour sdi consistence check est deja fait lors du docsprint : ) https://georchestra.gitbooks.io/data-admin/content/fr/guide-administrateur/geonetwork-catalogue/coherence-donnees-metadonnees.html 
pour le sviewer les contributions sont les bienvenues !

**Comment by jpklipfel** [comment]
Ah oui je n'avais pas vu

De toute façon il y a un espace discussion plus approprié ici on dirait
https://www.gitbook.com/book/georchestra/data-admin/discussions

**Comment by MaelREBOUX** [comment]
@zchicago je reformule

Pour la doc cadastrapp je conclue qu'il va falloir créé un nouveau dépôt https://github.com/georchestra/cadastrapp_doc/ 

Et un nouveau dépôt  https://github.com/sigrennesmetropole/addon_urbanisme_doc/ pour la doc sur le module urbanisme 

C'est bien ça ?

**Comment by fvanderbiest** [comment]
Yep.

**Comment by MaelREBOUX** [comment]
ok

**Comment by vbesand** [comment]
Bonjour à tous

Serait il possible que cette discussion ai lieu sur la liste principale 
?

En attendant bonne fête à tous
Valérie

Le 20/12/2017 14:51, > zoe Petty (par Internet, dépôt 
bounces+848413-3eec-valerie.besand=developpement-durable.gouv.fr@sgmail.github.com) 
a écrit :
